// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB6V4MYIsvwCa0BgPKN_o4Pjf1sLxj7Og',
    appId: '1:260616077959:web:a6c0986139fe23e0a0ee22',
    messagingSenderId: '260616077959',
    projectId: 'flutter-firebase-example-abdur',
    authDomain: 'flutter-firebase-example-abdur.firebaseapp.com',
    storageBucket: 'flutter-firebase-example-abdur.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LR68e72h6ZNr1JdWCzxERTeAm5QzPK8',
    appId: '1:260616077959:android:ead7ac76072e448da0ee22',
    messagingSenderId: '260616077959',
    projectId: 'flutter-firebase-example-abdur',
    storageBucket: 'flutter-firebase-example-abdur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVH1VOjMWl1HyzSNVuRd74p3PQrSeOeE',
    appId: '1:260616077959:ios:cb20ac88ed9dd00ca0ee22',
    messagingSenderId: '260616077959',
    projectId: 'flutter-firebase-example-abdur',
    storageBucket: 'flutter-firebase-example-abdur.appspot.com',
    iosClientId: '260616077959-3baosbeoshvbcrr1t18itce1ugqb3sh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCrashlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVH1VOjMWl1HyzSNVuRd74p3PQrSeOeE',
    appId: '1:260616077959:ios:cb20ac88ed9dd00ca0ee22',
    messagingSenderId: '260616077959',
    projectId: 'flutter-firebase-example-abdur',
    storageBucket: 'flutter-firebase-example-abdur.appspot.com',
    iosClientId: '260616077959-3baosbeoshvbcrr1t18itce1ugqb3sh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCrashlytics',
  );
}
